services:
  - type: web
    name: movietickets
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/Oblig3-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 10000
