services:
  - type: web
    name: movietickets-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    healthCheckGracePeriod: 300
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 10000
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m -Djava.security.egd=file:/dev/./urandom
